[package]
name = "script"
version = "0.1.0"
authors = ["Antoine32 <57961983+Antoine32@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]